### ISSUE TITLE
Problema com git push origin

### ISSUE THREAD

**Issue by lebuffet02** [F4NT0/ages-online-git#25]
Lucas Buffet - 20103333-9

Eu fiz os seguintes passos:
1 - git clone url;
2 - dentro do projeto da ages: git branch -b lucas-buffet;
3 - git push origin lucas-buffet -> erro abaixo;
remote: Permission to F4NT0/ages-online-git.git denied to lebuffet02.
fatal: unable to access 'https://github.com/F4NT0/ages-online-git/': The requested URL returned error: 403
4 - adicionei meu nome no arquivo listagem_alunos_aulagit.txt;
5 - git add listagem_alunos_aulagit.txt;
6 - git commit -m "criada a branch Lucas Buffet"
7 - git push origin lucas-buffet -> erro abaixo;
remote: Permission to F4NT0/ages-online-git.git denied to lebuffet02.
fatal: unable to access 'https://github.com/F4NT0/ages-online-git/': The requested URL returned error: 403

**Comment by F4NT0** [comment]
Olá @lebuffet02, eu esqueci que o meu Github é protegido e não tem como enviar modificações para os meus repos sem eu adicionar as pessoas como pessoas que podem alterar, portanto abra uma [Issue](https://github.com/F4NT0/ages-online-git/issues) com seu nome como as outras Issues que eu irei pegar seu nome

**Comment by F4NT0** [comment]
ja resolvido @lebuffet02, vi a sua primeira mensagem com o numero e nome
